### PR TITLE
Adding French translation to django.po

### PR DESCRIPTION
**Pull request by mireilleN**
Translation of Dublin Core elements was validated on the Bibliothèque nationale de France website: http://www.bnf.fr/fr/professionnels/formats_catalogage/a.f_dublin_core.html

Connects to #16.

### CODE REVIEW

**Comment by jraddaoui** [comment]
Hi @mireilleN,

I have fixed an issue with some strings that were ending abruptly with `//`. The translations you added for those "partial" strings have been removed from where they belong because the `msgid` has changed after the fix, including now the entire string. But those translations are in a commented section bellow. Once the full translation is added to the corresponding `msgstr`, those commented lines could be removed.

https://github.com/CCA-Public/dip-access-interface/blob/master/accesspoc/locale/fr/LC_MESSAGES/django.po#L866-L910

Sorry for the troubles.

**Comment by jraddaoui** [comment]
And the new messages are also added to the file, so it's ready for another round of translation.

Thanks @mireilleN!

**Comment by mireilleN** [comment]
Hi @jraddaoui!
Thanks for the follow-up and notes. 
I'll work on the next round of translation the week of September 17.

**Comment by mireilleN** [comment]
Hi @jraddaoui !

I submitted the PR , but there are 3 elements that I wanted to verify with you in order to confirm that the translations make sense. Could you provide me the context for the following terms/sentences:

Line 60 :
#: dips/models.py:29
msgid "Trace:"

Line 132 :
#: dips/models.py:226
msgid "A related TaskResult could not be found."

Line 842 :
#: templates/includes/header.html:4
msgid "Toggle navigation"

Where or when would those appear on the interface?

Thanks!

**Comment by jraddaoui** [comment]
Great question @mireilleN,

The first two may appear when there is an error in the in the Folder creation process. Now that you say it, I think it makes more sense to use "Error trace:" and "A related task result could not be found.". Please, let me know if you think that would be better and I'll change them alongside a few more strings that will be added in #104.

The last one is only used by screen readers to improve the accessibility of the header navigation in small resolutions. It will be read when the user focus the menu button in the header.

Thank you!

**Comment by jraddaoui** [comment]
Hi @mireilleN,

I have merged #104 and you can see what has been added to the messages files in ca871f0. Please, let me know if you want me to do the couple of changes I mentioned in the previous update.

Regards.

**Pull request merged**
